spring:
    datasource:
        url: jdbc:mysql://mysql.lvshuhuai.cn:3306/badminton_flash?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: lvzhi
        password: ENC(uJcujptsJM2XISNPFiTEGjUKS08qLtBN)
    data:
        redis:
            host: redis.lvshuhuai.cn
            port: 6379
            database: 2
    sql:
        init:
            mode: always
    rabbitmq:
        host: lvshuhuai.cn
        port: 5672
        username: guest
        password: guest
        virtual-host: /

jasypt:
    encryptor:
        password: prwq0421
        algorithm: PBEWITHMD5ANDDES
        bean: jasyptComputer

