app:
    timezone: Asia/Shanghai

spring:
    profiles:
        active: dev
    jackson:
        time-zone: ${app.timezone}
server:
    port: 25001
logging:
    charset:
        console: UTF-8
        file: UTF-8
