spring:
    datasource:
        url: jdbc:mysql://mysql.lvshuhuai.cn:3306/badminton_flash?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=${app.timezone}
        username: lvzhi
        password: ENC(uJcujptsJM2XISNPFiTEGjUKS08qLtBN)
    data:
        redis:
            host: redis.lvshuhuai.cn
            port: 6379
            database: 2
    sql:
        init:
            mode: always
    rabbitmq:
        host: lvshuhuai.cn
        port: 5672
        username: lvzhi
        password: ENC(uJcujptsJM2XISNPFiTEGjUKS08qLtBN)
        virtual-host: /
